# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.FloatField(default=0.0, verbose_name=' Mean of the Normal Distribution: ')),
                ('s', models.FloatField(default=1.0, verbose_name=' Standard Deviation of the Normal Distribution (strictly positive):   ')),
            ],
        ),
        migrations.CreateModel(
            name='Predict_Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.FloatField(default=-1.0, verbose_name=' Lower bound:  ')),
                ('p2', models.FloatField(default=1.0, verbose_name=' Upper bound:  ')),
            ],
        ),
        migrations.CreateModel(
            name='Sample_Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.FloatField(default=1, verbose_name=' Number of samples you wish to draw:')),
            ],
        ),
    ]
